<?php  
class Constants {
	const $GENDER_TYPE_MALE = 0;
	const $GENDER_TYPE_FEMALE = 1;

	const $ACCOMMODATION_TYPE_SINGLE = 1;
	const $ACCOMMODATION_TYPE_DOUBLE_WHOLE = 2;
	const $ACCOMMODATION_TYPE_DOUBLE_HALF = 3;
	const $ACCOMMODATION_TYPE_NONE = 4;

	const $PROJECT_TYPE_TRANSACTION = 1;
	const $PROJECT_TYPE_MEETING = 2;
	const $PROJECT_TYPE_TRAINING = 3;

	const $FEE_TYPE_BANK = 1;
	const $FEE_TYPE_SCENE = 2;
}
?>